<?php

namespace ContainerT9rDwGm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EETwEHGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EETwEHG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EETwEHG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'materiel' => ['privates', '.errored..service_locator.EETwEHG.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.EETwEHG": it needs an instance of "App\\Entity\\Materiel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'materiel' => 'App\\Entity\\Materiel',
        ]);
    }
}
